runtime: python
env: flex

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

runtime_config:
  python_version: 3.9

automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10