name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.7.0
        with:
          project_id: upbeat-polygon-450719-a6
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud config set project upbeat-polygon-450719-a6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Google Compute Engine
        run: |
          gcloud compute ssh --zone "us-central1-a" "fastapi-book-project" --project "upbeat-polygon-450719-a6" --command "cd /home/your-user/fastapi-book-project && git pull && sudo systemctl restart fastapi-app"