name: Deploy to production

on:
  push:
  branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to production
      run: |
        ssh ssh user@your-server-ip "cd /path/to/your/app && git pull origin main && systemctl restart fastapi-app"
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}