name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set a timeout for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest /tests --maxfail=1 --disable-warnings -v

      - name: Debugging
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set Project
        run: |
          gcloud config set project upbeat-polygon-450719-a6

      - name: Initialize App Engine
        run: |
          gcloud app create --region=us-central || echo "App Engine already exists"

      - name: Deploy to Google Cloud
        run: |
          gcloud app deploy --quiet

      - name: Check deployment logs
        run: |
          gcloud app logs read --limit=100